FROM golang:latest AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o news-api cmd/news-api/main.go

FROM scratch
COPY --from=builder /app/news-api .
EXPOSE 8080
CMD ["./news-api"]