FROM golang:latest as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o news-storage cmd/news-storage/main.go

FROM scratch
COPY --from=builder /app/news-storage .
CMD ["./news-storage"]