FROM golang:latest as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go build -o news-api cmd/news-api/main.go

FROM scratch
COPY --from=builder /app/news-api /app/
EXPOSE 8080
ENTRYPOINT ["/app/news-api"]