FROM golang:latest as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go build -o news-storage cmd/news-storage/main.go

FROM scratch
COPY --from=builder /app/news-storage /app/
ENTRYPOINT ["/app/news-storage"]