version: '3'
services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news
  news-api:
    ports:
      - "8080:8080"
    environment:
      API_BINDING: ":8080"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news
    build:
      context: .
      dockerfile: Dockerfile.news-api
    depends_on:
      - gnatsd
  news-storage:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news
      WAIT_HOSTS: gnatsd:4222
    build:
      context: .
      dockerfile: Dockerfile.news-storage
    depends_on:
      - gnatsd
      - db
  gnatsd:
    image: "nats:latest"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"