// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mess.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewsReq_Action int32

const (
	NewsReq_GET  NewsReq_Action = 0
	NewsReq_PUT  NewsReq_Action = 1
	NewsReq_POST NewsReq_Action = 2
)

var NewsReq_Action_name = map[int32]string{
	0: "GET",
	1: "PUT",
	2: "POST",
}

var NewsReq_Action_value = map[string]int32{
	"GET":  0,
	"PUT":  1,
	"POST": 2,
}

func (x NewsReq_Action) String() string {
	return proto.EnumName(NewsReq_Action_name, int32(x))
}

func (NewsReq_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c78b50d87ecacffe, []int{0, 0}
}

type NewsReq struct {
	Action               NewsReq_Action `protobuf:"varint,2,opt,name=action,proto3,enum=internal.NewsReq_Action" json:"action,omitempty"`
	Item                 *NewsItem      `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	JobId                int64          `protobuf:"varint,6,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NewsReq) Reset()         { *m = NewsReq{} }
func (m *NewsReq) String() string { return proto.CompactTextString(m) }
func (*NewsReq) ProtoMessage()    {}
func (*NewsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c78b50d87ecacffe, []int{0}
}

func (m *NewsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewsReq.Unmarshal(m, b)
}
func (m *NewsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewsReq.Marshal(b, m, deterministic)
}
func (m *NewsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewsReq.Merge(m, src)
}
func (m *NewsReq) XXX_Size() int {
	return xxx_messageInfo_NewsReq.Size(m)
}
func (m *NewsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NewsReq.DiscardUnknown(m)
}

var xxx_messageInfo_NewsReq proto.InternalMessageInfo

func (m *NewsReq) GetAction() NewsReq_Action {
	if m != nil {
		return m.Action
	}
	return NewsReq_GET
}

func (m *NewsReq) GetItem() *NewsItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *NewsReq) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type NewsRes struct {
	Success              bool        `protobuf:"varint,10,opt,name=success,proto3" json:"success,omitempty"`
	Error                string      `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	Item                 []*NewsItem `protobuf:"bytes,14,rep,name=item,proto3" json:"item,omitempty"`
	JobId                int64       `protobuf:"varint,16,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NewsRes) Reset()         { *m = NewsRes{} }
func (m *NewsRes) String() string { return proto.CompactTextString(m) }
func (*NewsRes) ProtoMessage()    {}
func (*NewsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c78b50d87ecacffe, []int{1}
}

func (m *NewsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewsRes.Unmarshal(m, b)
}
func (m *NewsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewsRes.Marshal(b, m, deterministic)
}
func (m *NewsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewsRes.Merge(m, src)
}
func (m *NewsRes) XXX_Size() int {
	return xxx_messageInfo_NewsRes.Size(m)
}
func (m *NewsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_NewsRes.DiscardUnknown(m)
}

var xxx_messageInfo_NewsRes proto.InternalMessageInfo

func (m *NewsRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *NewsRes) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *NewsRes) GetItem() []*NewsItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *NewsRes) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type NewsItem struct {
	TimeStamp            string   `protobuf:"bytes,2,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	Header               string   `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int64    `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewsItem) Reset()         { *m = NewsItem{} }
func (m *NewsItem) String() string { return proto.CompactTextString(m) }
func (*NewsItem) ProtoMessage()    {}
func (*NewsItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c78b50d87ecacffe, []int{2}
}

func (m *NewsItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewsItem.Unmarshal(m, b)
}
func (m *NewsItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewsItem.Marshal(b, m, deterministic)
}
func (m *NewsItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewsItem.Merge(m, src)
}
func (m *NewsItem) XXX_Size() int {
	return xxx_messageInfo_NewsItem.Size(m)
}
func (m *NewsItem) XXX_DiscardUnknown() {
	xxx_messageInfo_NewsItem.DiscardUnknown(m)
}

var xxx_messageInfo_NewsItem proto.InternalMessageInfo

func (m *NewsItem) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

func (m *NewsItem) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *NewsItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("internal.NewsReq_Action", NewsReq_Action_name, NewsReq_Action_value)
	proto.RegisterType((*NewsReq)(nil), "internal.NewsReq")
	proto.RegisterType((*NewsRes)(nil), "internal.NewsRes")
	proto.RegisterType((*NewsItem)(nil), "internal.NewsItem")
}

func init() { proto.RegisterFile("mess.proto", fileDescriptor_c78b50d87ecacffe) }

var fileDescriptor_c78b50d87ecacffe = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4a, 0xf4, 0x30,
	0x14, 0x86, 0xbf, 0xb4, 0x9d, 0xb4, 0x3d, 0x9f, 0x94, 0x72, 0x50, 0xc9, 0x46, 0x08, 0x45, 0xa4,
	0xab, 0x22, 0xe3, 0x15, 0xb8, 0x10, 0x99, 0x8d, 0x8e, 0x99, 0xba, 0x1e, 0xfa, 0x13, 0x30, 0x83,
	0x6d, 0xc6, 0x24, 0xa2, 0x97, 0xe3, 0xa5, 0x4a, 0x3b, 0xed, 0xa0, 0x3b, 0x77, 0x79, 0xcf, 0x79,
	0x08, 0x4f, 0xde, 0x00, 0x74, 0xd2, 0xda, 0x62, 0x6f, 0xb4, 0xd3, 0x18, 0xa9, 0xde, 0x49, 0xd3,
	0x57, 0xaf, 0xd9, 0x17, 0x81, 0xf0, 0x41, 0x7e, 0x58, 0x21, 0xdf, 0xf0, 0x1a, 0x68, 0xd5, 0x38,
	0xa5, 0x7b, 0xe6, 0x71, 0x92, 0x27, 0x4b, 0x56, 0xcc, 0x58, 0x31, 0x21, 0xc5, 0xed, 0xb8, 0x17,
	0x13, 0x87, 0x57, 0x10, 0x28, 0x27, 0x3b, 0x16, 0x70, 0x92, 0xff, 0x5f, 0xe2, 0x6f, 0x7e, 0xe5,
	0x64, 0x27, 0xc6, 0x3d, 0x9e, 0x01, 0xdd, 0xe9, 0x7a, 0xab, 0x5a, 0x46, 0x39, 0xc9, 0x7d, 0xb1,
	0xd8, 0xe9, 0x7a, 0xd5, 0x66, 0x97, 0x40, 0x0f, 0x17, 0x62, 0x08, 0xfe, 0xfd, 0x5d, 0x99, 0xfe,
	0x1b, 0x0e, 0xeb, 0xe7, 0x32, 0x25, 0x18, 0x41, 0xb0, 0x7e, 0xdc, 0x94, 0xa9, 0x97, 0x7d, 0xce,
	0x86, 0x16, 0x19, 0x84, 0xf6, 0xbd, 0x69, 0xa4, 0xb5, 0x0c, 0x38, 0xc9, 0x23, 0x31, 0x47, 0x3c,
	0x85, 0x85, 0x34, 0x46, 0x1b, 0x76, 0xc2, 0x49, 0x1e, 0x8b, 0x43, 0x38, 0xfa, 0x25, 0xdc, 0xff,
	0xa3, 0x5f, 0xfa, 0xd3, 0xef, 0x09, 0xa2, 0x19, 0xc4, 0x0b, 0x00, 0xa7, 0x3a, 0xb9, 0xb5, 0xae,
	0xea, 0xf6, 0x63, 0x41, 0xb1, 0x88, 0x87, 0xc9, 0x66, 0x18, 0xe0, 0x39, 0xd0, 0x17, 0x59, 0xb5,
	0xd2, 0x8c, 0x5d, 0xc4, 0x62, 0x4a, 0x98, 0x80, 0x77, 0x7c, 0xb5, 0xa7, 0xda, 0x9a, 0x8e, 0x1f,
	0x70, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x17, 0xa3, 0x96, 0x76, 0x8e, 0x01, 0x00, 0x00,
}
